name: CI

on:
  push:
  pull_request:

jobs:
  macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: brew install xcodegen librsvg
      - name: Run CI script
        run: ./scripts/ci/ci.sh
